studentdatabase/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'main'

urlpatterns = [
    path("", views.homepage, name = 'homepage'),
    path("register/", views.register, name = 'register'),
    path("logout/", views.logout_request, name = 'logout'),
    path("login/", views.login_request, name = 'login'),
    path("addstudent/", views.addstudent, name = 'addstudent'),
    path("updatestudent/<str:pk>/", views.updatestudent, name = 'updatestudent'),
    path("deletestudent/<str:pk>/", views.deletestudent, name = 'deletestudent'),
    path("academics/<str:pk>/", views.StudentInfoDetailView.as_view(), name='academics'),
    path("searchstudent/", views.searchstudent, name = 'searchstudent'),
    path('websearch/', views.websearch, name='websearch'),
    path('websearch/search', views.search, name='search'),
    path("edit_profile/", views.UserEditView.as_view(), name = 'edit_profile'),
    path("password/", views.PasswordsChangeView.as_view(template_name = 'main/change-password.html')),
]

studentdatabase/studentdatabase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

studentdatabase/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class StudentInfo(models.Model):
    StudentRollNumber = models.CharField(max_length=10)
    StudentName  = models.CharField(max_length=50)
    StudentClass  = models.CharField(max_length=50,null=True)
    StudentSchool  = models.CharField(max_length=50,null=True)
    StudentMobile = models.IntegerField(validators=[MinValueValidator(999999999), MaxValueValidator(9999999999)], null=True)
    StudentAddress  = models.CharField(max_length=50,null=True)
    MathMarks  = models.IntegerField(null=True)
    PhysicsMarks = models.IntegerField(null=True)
    ChemistryMarks  = models.IntegerField(null=True)
    BioMarks  = models.IntegerField(null=True)
    EnglishMarks  = models.IntegerField(null=True)

    def __str__(self):
        return self.StudentRollNumber

studentdatabase/main/forms.py
from dataclasses import field
from pyexpat import model
from turtle import textinput
from typing import Text, TextIO
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from.models import *

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class StudentInfoForm(forms.ModelForm):
    StudentRollNumber = forms.CharField(label='Roll Number')
    StudentName  = forms.CharField(label='Name')
    StudentClass  = forms.CharField(label='Class Name')
    StudentSchool  = forms.CharField(label='School Name')
    StudentMobile = forms.IntegerField(label='Mobile Number')
    StudentAddress  = forms.CharField(label='Address')
    MathMarks  = forms.IntegerField(label='Math Marks')
    PhysicsMarks = forms.IntegerField(label='Physics Marks')
    ChemistryMarks  = forms.IntegerField(label='Chemistry Marks')
    BioMarks  = forms.IntegerField(label='Biology Marks')
    EnglishMarks = forms.IntegerField(label='English Marks') 


    class Meta:
        model = StudentInfo
        #fields = '__all__'
        fields = ["StudentRollNumber", "StudentName",  "StudentClass",  "StudentSchool",  "StudentMobile",  "StudentAddress",  "MathMarks",  "PhysicsMarks",  "ChemistryMarks",  "BioMarks",  "EnglishMarks"]

    def clean_StudentRollNumber(self): # Validates the Computer Name Field
        StudentRollNumber = self.cleaned_data.get('StudentRollNumber')
        if (StudentRollNumber == ""):
            raise forms.ValidationError('This field cannot be left blank')

        for instance in StudentInfo.objects.all():
            if instance.StudentRollNumber == StudentRollNumber:
                raise forms.ValidationError(StudentRollNumber + ' is already added')
    
        return StudentRollNumber

class EditProfileForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_login = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    date_joined = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'last_login', 'date_joined')

studentdatabase/main/views.py
from multiprocessing import context
from re import template
from tkinter.tix import InputOnly
from urllib import request
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import *
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import *
from django.views import generic
from django.views.generic import DetailView
import requests
from bs4 import BeautifulSoup as bs
from django.urls import reverse_lazy


# Create your views here.

def homepage(request):
    return render(request=request,
                    template_name="main/home.html",
                    context={"studentinfo":StudentInfo.objects.all})


def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"New Account Created: {username}")
            login(request, user)
            messages.info(request, f"You are now logged in as {username}")
            return redirect("main:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

    form = NewUserForm
    return render(request,
                    "main/register.html",
                    context={"form":form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("main:homepage")


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"You are now logged in as {username}")
                return redirect("main:homepage")
            else:
                messages.error(request, f"Invalid username or password")

        else:
            messages.error(request, f"Invalid username or password")
    form = AuthenticationForm()
    return render(request,
                    "main/login.html",
                    context={"form":form})

def addstudent(request):
    studentinfos = StudentInfo.objects.all()
    form = StudentInfoForm()
    if request.method=="POST":
        form = StudentInfoForm(request.POST or None)
        if form.is_valid():
            form.save()
            #messages.success(request, f"{studentinfos} Added Successfully")
        return redirect('main:homepage')
    return render(request,
                    "main/addstudent.html",
                    context={"studentinfos":studentinfos, "form":form})

def updatestudent(request, pk):
    studentinfos = StudentInfo.objects.get(id=pk)
    form = StudentInfoForm(instance=studentinfos)

    if request.method == "POST":
        form = StudentInfoForm(request.POST, instance=studentinfos)
        if form.is_valid():
            form.save()
            messages.success(request, f"{studentinfos} Updated Successfully")
            return redirect('main:homepage')
        
    return render(request,
                    "main/updatestudent.html",
                    context={"form":form}
                    )

def deletestudent(request, pk):
    studentinfos = StudentInfo.objects.get(id=pk)
    #form = StudentInfoForm(instance=studentinfos)
    if request.method == "POST":
        studentinfos.delete()
        messages.success(request, f"{studentinfos} Deleted Successfully")
        return redirect('main:homepage')
    return render(request,
                    'main/deletestudent.html',
                    {"studentinfos":studentinfos})

class StudentInfoDetailView(DetailView):
    template_name = 'main/academics.html'
    queryset = StudentInfo.objects.all()

def searchstudent(request):
    if request.method == "POST":
        searched = request.POST["searched"]
        studentnames = StudentInfo.objects.filter(StudentName__contains=searched)

        return render(request,
                    'main/searchstudent.html',
                    {"searched":searched, "studentnames":studentnames})
    else:
        return render(request,
                    'main/searchstudent.html',
                    {})

def websearch(request):
    return render(request,
                    'main/websearch.html',
                    {})


def search(request):
    if request.method == 'POST':
        search = request.POST['search']
        url = search
        res = requests.get(url)
        soup = bs(res.text, 'html.parser')

        final_result = []
        for link in soup.find_all('a'):
            result_url = link.get('href')

            final_result.append(result_url)


        context = {
            'final_result': final_result
        }

        return render(request, 'main/search.html', context)

    else:
        return render(request, 'main/search.html')


class UserEditView(generic.UpdateView):
    form_class = EditProfileForm
    template_name = 'main/edit_profile.html'
    success_url = reverse_lazy('main:homepage')

    def get_object(self):
        return self.request.user

class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('main:homepage')

studentdatabase/main/templates/main/academics.html
{% extends "main/header.html" %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <h5><strong>{{object.StudentName}}</strong></h5>
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Roll Number</th>
                    <td>{{object.StudentRollNumber}} </td>
                </tr>
                <tr>    
                    <th>Name</th>
                    <td>{{object.StudentName}} </td>
                </tr>
                <tr>    
                    <th>Class</th>                    
                    <td>{{object.StudentClass}} </td>
                </tr>
                <tr>    
                    <th>School</th>
                    <td>{{object.StudentSchool}} </td>
                </tr>
                <tr>    
                    <th>Mobile Number</th>
                    <td>{{object.StudentMobile}} </td>
                </tr>
                <tr>    
                    <th>Address</th>
                    <td>{{object.StudentAddress}} </td>
                </tr>
                <tr>
                    <th>Math Marks</th>
                    <td>{{object.MathMarks}} </td>
                </tr>
                <tr>
                    <th>Physics Marks</th>
                    <td>{{object.PhysicsMarks}} </td>
                </tr>
                <tr>
                    <th>Chemistry Marks</th>      
                    <td>{{object.ChemistryMarks}} </td>
                </tr>
                <tr>
                    <th>Biology Marks</th>      
                    <td>{{object.BioMarks}} </td>
                </tr>
                <tr>
                    <th>English Marks</th>      
                    <td>{{object.EnglishMarks}} </td>
                </tr>
            </table>
            <p> <b>Note:</b> Marks are out of 100</p>
        </div>
    </div>
</div>                    
{% endblock %}

studentdatabase/main/templates/main/addstudent.html
{% extends "main/header.html" %}

{% block content %}
    
    <form method="POST">
        {% csrf_token %}
        
        {{form.as_p}}
    
        <button class="btn" style="background-color:black" type="submit" name="Create Task">Submit</button>
    </form>


{% endblock %}

studentdatabase/main/templates/main/change-password.html
{% extends "main/header.html" %}

{% block content %}
    
    <form method="POST">
        {% csrf_token %}
        
        {{form.as_p}}
    
        <button class="btn" style="background-color:black" type="submit">Change Password</button>
    </form>

{% endblock %}

studentdatabase/main/templates/main/deletestudent.html
{% extends "main/header.html" %}

{% block content %}
    
    <div class="center">
    <p>Are you sure you want to delete "{{studentinfos}}"?</p>
    
    <form method="POST" action="">
    
        {% csrf_token %}    
        <button class="btn" style="background-color:rgb(150, 0, 0)" type="submit" name="Confirm">Submit</button>
        <a class="btn" style="background-color:rgb(0, 110, 0)" href="{% url 'main:homepage' %}">Cancel</a>
    </form>
</div>


{% endblock %}

studentdatabase/main/templates/main/edit_profile.html
{% extends 'main/header.html' %}

{% block content %}
    <br>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button style="background-color:black; color:white" class="btn btn-outline-info" type="submit">Update Profile</button>
    </form>

{% endblock %}

studentdatabase/main/templates/main/header.html
<head>
    {% load static %}
    <!-- Compiled and minified CSS -->
    <link href="{% static 'main/css/materialize.css' %}" rel="stylesheet">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  {% include "main/includes/navbar.html" %}
  <br><br>
  {% include "main/includes/messages.html" %}
    <div class="container ">

      {% block content %}
      {% endblock %}

    </div>
</body>

studentdatabase/main/templates/main/home.html
{% extends "main/header.html" %}

{% block content %}


    <br><br>
 
    <div class="row">
        <div class="col-md-9">
            
        
            <div class="card card-body">
                <table class="table table-sm">
                    <tr>
                        <th>Roll Number</th>
                        <th>Name</th>
                        <th>Class</th>                    
                        <th>School</th>
                        <th>Mobile Number</th>
                        <th>Address</th>
                        
                    </tr>
                    {% for a in studentinfo %}
                        <tr>
                            <td>{{a.StudentRollNumber}} </td>
                            {% if user.is_authenticated %}
                            <td><a href="{% url 'main:academics' a.id %}">{{a.StudentName}}</a></td>
                            {% else %}
                            <td>{{a.StudentName}}</td>
                            {% endif %}
                            <td>{{a.StudentClass}} </td>
                            <td>{{a.StudentSchool}} </td>
                            <td>{{a.StudentMobile}} </td>
                            <td>{{a.StudentAddress}} </td>
                            {% if user.is_authenticated %}
                                <td><a class="btn" style="background-color:rgb(0, 110, 0)" href="{% url 'main:updatestudent' a.id %}">Update</a></td>
                                <td><a class="btn" style="background-color:rgb(150, 0, 0)" href="{% url 'main:deletestudent' a.id %}">Delete</a></td>
                            {% endif %}
                        </tr>
                
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
 
    <br><br>
 
{% endblock %}

studentdatabase/main/templates/main/login.html
{% extends "main/header.html" %}

{% block content %}
    
    <form method="POST">
        {% csrf_token %}
        
        {{form.as_p}}
    
        <button class="btn" style="background-color:black" type="submit">Login</button>
    </form>


    If you don't have an account, <a href="/register"><strong>register</strong></a> for one.

{% endblock %}

studentdatabase/main/templates/main/register.html
{% extends 'main/header.html' %}

{% block content %}
    <br>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button style="background-color:black; color:white" class="btn btn-outline-info" type="submit">Sign Up</button>
    </form>

    If you already have an account <a href="/login" target="blank"><strong>login</strong></a> instead.

{% endblock %}

studentdatabase/main/templates/main/search.html
{% extends "main/header.html" %}

{% block content %}

    <center><h3>Links/URLs</h3></center>
    <br/><br/><br/><br/><br/><br/>
    <div class="search">
        <form method="POST" action="search">
                {% csrf_token %}
                {{form.as_p}}
            <input class="search-bar" type="text" name="search" autofocus x-webkit-speech/>
            <div class="search-nav">
                <div class="search-button center">
                    <a href="#"><button type="submit" style="height:50px;width:100px"><strong>Get Links</strong></button></a>
                </div>
            </div>
        </form>   
    </div>

    {% if final_result %}
        <b style="padding-left: 50px; padding-right: 50px; color: #646464;">Links/URLs</b>
        {% for result in final_result %}
            <div style="padding-left: 50px; padding-right: 50px;">
                <h6 style="color: blue;"><a href="{{ result }}">{{ result }}</a></h3>
            </div>
        {% endfor %}
    {% endif %}

{% endblock %}

studentdatabase/main/templates/main/searchstudent.html
{% extends "main/header.html" %}

{% block content %}
    <div class="center">
        {% if searched %}
            <h4>You searched for "{{searched}}"</h4><br/>
            <div class="card card-body">
                <table class="table table-sm">  
                    <tr>
                        <th>Roll Number</th>
                        <th>Name</th>
                        <th>Class</th>                    
                        <th>School</th>
                        <th>Mobile Number</th>
                        <th>Address</th>
                    </tr>
                    {% for a in studentnames %}
                        <tr>
                            <td>{{a.StudentRollNumber}} </td>
                            {% if user.is_authenticated %}
                            <td><a href="{% url 'main:academics' a.id %}">{{a.StudentName}}</a></td>
                            {% else %}
                            <td>{{a.StudentName}}</td>
                            {% endif %}
                            <td>{{a.StudentClass}} </td>
                            <td>{{a.StudentSchool}} </td>
                            <td>{{a.StudentMobile}} </td>
                            <td>{{a.StudentAddress}} </td>
                            {% if user.is_authenticated %}
                                <td><a class="btn" style="background-color:rgb(0, 110, 0)" href="{% url 'main:updatestudent' a.id %}">Update</a></td>
                                <td><a class="btn" style="background-color:rgb(150, 0, 0)" href="{% url 'main:deletestudent' a.id %}">Delete</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
        {% else %}
            <h4>You forgot to search for a student!</h4>
        {% endif %}
    </div>
{% endblock %}

studentdatabase/main/templates/main/updatestudent.html
{% extends "main/header.html" %}

{% block content %}
    
    <form method="POST">
    
        {% csrf_token %}
        
        {{form.as_p}}
    
    
        <button class="btn" style="background-color:black" type="submit" name="Create Task">Submit</button>
    </form>


{% endblock %}

studentdatabase/main/templates/main/websearch.html
{% extends "main/header.html" %}

{% block content %}

<center><h3>Links/URLs</h3></center>
<br/><br/><br/><br/><br/><br/>
<div class="search">
    <form method="POST" action="search">
            {% csrf_token %}
            {{form.as_p}}
        <input class="search-bar" type="text" name="search" autofocus x-webkit-speech/>
        <div class="search-nav">
            <div class="search-button center"><a href="#">
                <button type="submit" style="height:50px;width:100px"><strong>Get Links</strong></button></a>
            </div>
        </div>
    </form>
</div>
  
{% endblock %}